ignore:
  - .git
  - node_modules
  - dist
  - coverage
  - "**/__tests__/**"
  - "**/*.test.ts"
  - "**/*.spec.ts"

rule_settings:
  enable: [default]
  disable:
    - for-append-to-extend
    - raise-from-previous-error
    - low-code-quality
  rule_types:
    - refactoring
    - suggestion
    - comment

metrics:
  quality_threshold: 30.0

rule_tags:
  pre-commit:
    - stylistic
    - critical-rules
  critical-rules:
    - use-literals
    - use-comprehensions

rules:
  - id: avoid-hardcoded-credentials
    description: Use environment variables instead of hardcoding credentials
    pattern: "password: .*"
    replacement: "password: ${DB_PASSWORD}"
    paths:
      include:
        - "**/app-config.yaml"
    tags:
      - critical-rules
    tests:
      - match: |
          password: "secret"
        expect: |
          password: ${DB_PASSWORD}

github:
  labels: []
  ignore_labels:
    - sourcery-ignore
  request_review: author
  sourcery_branch: sourcery/{base_branch}

clone_detection:
  min_lines: 5
  min_duplicates: 2
  identical_clones_only: true
